#!/usr/bin/env python
#
# Copyright (C) 2025 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import os
import subprocess
import sys

"""
This script runs all of Torq's unit tests specified in
the BUILD file.

All tests can be run with:
    ./torq_test

The Bazel build system is used.

You can filter to only run specific tests with:
    ./torq_test torq_unit_test device_unit_test
"""
if __name__ == "__main__":
  # Get test filters, excluding the script name
  args = sys.argv[1:]
  filter_tests = args

  cmd = ['bazel', 'test', '--test_output=errors']

  # Apply filters or run all tests
  if len(filter_tests) > 0:
      cmd += [f"//:{test}" for test in filter_tests]
  else:
      cmd.append(':all')

  print(f"Command: {" ".join(cmd)}")
  subprocess.run(cmd)
  sys.exit(0)
