#!/usr/bin/env python
#
# Copyright (C) 2025 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""
This script runs all of Torq's unit and integration tests
specified in the BUILD file.

All tests can be run with:
    ./torq_test --all

Integration tests can be run with:
    ./torq_test --integration

Unit tests can be run with:
    ./torq_test --unit
    ./torq_test

You can filter to only run specific unit tests with:
    ./torq_test --unit torq_unit_test device_unit_test
"""

import os
import subprocess
import sys
import argparse

def parse_args():
    parser = argparse.ArgumentParser(description="Run torq tests.")
    group = parser.add_mutually_exclusive_group()

    group.add_argument("--unit", action="store_const", dest='test_mode',
                       const='unit', help="Run unit tests.")
    group.add_argument("--integration", action="store_const", dest='test_mode',
                       const='integration', help="Run integration tests.")
    group.add_argument("--all", action="store_const", dest='test_mode',
                       const='all', help="Run all tests (unit + integration).")
    parser.set_defaults(test_mode='unit')

    parser.add_argument(
        "remaining",
        nargs="*",
        help="Specific individual unit-test names to run."
    )
    return parser.parse_args()

def run_tests(args):
    cmd = ["bazel", "test", "--test_output=errors"]

    if args.test_mode != "all":
      cmd.append(f"--test_tag_filters={args.test_mode}")

    if args.test_mode == "integration" or args.test_mode == "all":
        cmd.extend([f"--action_env=PATH={os.environ.get('PATH', '')}",])

    cmd.extend(args.remaining if args.remaining else ["//:all"])

    print(f"\n--- Running {args.test_mode} Tests: ---")

    result = subprocess.run(cmd)
    return result.returncode

if __name__ == "__main__":
    test_args = parse_args()
    status = run_tests(test_args)
    sys.exit(status)